# Generated by Django 3.0.1 on 2019-12-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='暂无描述'),
        ),
        migrations.AddField(
            model_name='course',
            name='notification',
            field=models.TextField(default='暂无公告'),
        ),
        migrations.AddField(
            model_name='course',
            name='reference',
            field=models.TextField(default='暂无参考'),
        ),
    ]
