# Generated by Django 3.0.1 on 2019-12-27 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20191228_0004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
