# Generated by Django 3.0.1 on 2019-12-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_auto_20191229_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='No description yet.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='notification',
            field=models.TextField(default='No notification yet.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='reference',
            field=models.TextField(default='No reference yet.'),
        ),
    ]
