# Generated by Django 2.2.7 on 2019-12-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('passwords', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('identity', models.CharField(default='学生', max_length=2)),
            ],
        ),
    ]
