# Generated by Django 2.2.7 on 2019-12-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_reg',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
