# Generated by Django 3.0.1 on 2019-12-29 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign1', '0004_auto_20191229_1103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='courses',
        ),
    ]
