# Generated by Django 3.0.1 on 2019-12-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign1', '0005_delete_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_reg',
            name='identity',
            field=models.CharField(default='Student', max_length=10),
        ),
    ]
