# Generated by Django 2.2.7 on 2019-12-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_name', models.CharField(max_length=20)),
                ('hw_content', models.CharField(max_length=100)),
                ('hw_content_details', models.CharField(max_length=255)),
            ],
        ),
    ]
