# Generated by Django 2.2.7 on 2019-12-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20191229_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='courses_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='courses',
            name='student_id',
            field=models.IntegerField(default=1),
        ),
    ]
