# Generated by Django 3.0.1 on 2019-12-29 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_teacher_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='courses',
        ),
        migrations.DeleteModel(
            name='teacher',
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
