# Generated by Django 3.0.1 on 2019-12-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20191229_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses_code',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20),
        ),
    ]
